export const SET_GAME_STATUS = 'SET_GAME_STATUS';
export const SET_GAME_MODES = 'SET_GAME_MODES';
export const SET_CURRENT_MODE = 'SET_CURRENT_MODE';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_LIDER_BOARD = 'SET_LIDER_BOARD';
export const RESET_GAME = 'RESET_GAME';
